app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
 
// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);

Route::get('/', 'ClienteController@index');
#Route::get('/', function () {
#    return view('app');
#});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'api', 'namespace' => 'API'], function ()
{
	Route::group(['prefix' => ''], function ()
	{
        require Config::get('generator.path_api_routes');
	});
});

Route::get('clientes/{id}/delete', [
    'as' => 'clientes.delete',
    'uses' => 'ClienteController@destroy',
]);
Route::resource('clientes', 'ClienteController');

Route::get('facturas/facturar', [
            'as'   => 'facturas.facturar',
            'uses' => 'FacturaController@facturar'
]);
Route::post('facturas/facturar', [
            'as'   => 'facturas.facturar',
            'uses' => 'FacturaController@facturar'
]);

Route::get('facturas/imprimir', 'FacturaController@imprimir');
Route::post('facturas/imprimir', [
            'as'   => 'facturas.imprimir',
            'uses' => 'FacturaController@imprimir'
]);

Route::post('facturas/getPendientesFacturacion', 'FacturaController@getPendientesFacturacion');
Route::post('facturas/facturarBySucursal', 'FacturaController@facturarBySucursal');
Route::get('facturas/facturarAfip', 'FacturaController@facturarAfip');

Route::get('facturas/facturacion', [
            'as'   => 'facturas.facturacion',
            'uses' => 'FacturaController@facturacion'
]);
Route::resource('facturas', 'FacturaController');

Route::resource('servicios', 'ServicioController');

Route::get('localidad/getLocalidadesAutocomplete', 'LocalidadController@getLocalidadesAutocomplete');

Route::resource('domicilios_cliente', 'DomicilioClienteController');

Route::get('sucursales/getDatosClienteFactura', 'SucursalController@getDatosClienteFactura');
Route::get('sucursales/getSucursalesAutocomplete', 'SucursalController@getSucursalesAutocomplete');
Route::get('sucursales/getSucursalesActivasAutocomplete', 'SucursalController@getSucursalesActivasAutocomplete');
Route::get('sucursales/getSucursalesActivasByNroClienteAutocomplete', 'SucursalController@getSucursalesActivasByNroClienteAutocomplete');
Route::resource('sucursales', 'SucursalController');


Route::get('productos/getProductosAutocomplete', 'ProductoController@getProductosAutocomplete');
Route::resource('productos', 'ProductoController');

Route::get('productos/{id}/delete', [
    'as' => 'productos.delete',
    'uses' => 'ProductoController@destroy',
]);

Route::get('politicas_producto/getProductosBySucursal', 'PoliticaProductoController@getProductosBySucursal');
Route::get('politicas_producto/getProductosBySucursalAutocomplete', 'PoliticaProductoController@getProductosBySucursalAutocomplete');
Route::resource('politicas_producto', 'PoliticaProductoController');

Route::get('politicas_producto/{id}/delete', [
    'as' => 'politicas_producto.delete',
    'uses' => 'PoliticaProductoController@destroy',
]);

Route::get('politicas_precios/getPrecioForItem', 'PoliticaPrecioController@getPrecioForItem');

/*
Route::get('clientes/{id}/delete', [
    'as' => 'clientes.delete',
    'uses' => 'ClienteController@destroy',
]);
*/

resources/views/sucursales/create.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'sucursales.store']) !!}

        @include('sucursales.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/sucursales/edit.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($sucursal, ['route' => ['sucursales.update', $sucursal->id], 'method' => 'patch']) !!}

        @include('sucursales.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/sucursales/fields.blade.php
<div class="col-sm-6 col-lg-6 form-horizontal">

    @if (!isset($sucursal))
        {!! Form::hidden('cliente_id', $options['cliente'], ['class' => 'form-control']) !!}
    @endif
    
    {!! Form::hidden('localidad_id', null, ['id' => 'localidad_id', 'class' => 'form-control']) !!}

    <div class="form-group">
        {!! Form::label('nombre', 'Nombre', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('nro_ceamse', 'Nro. Ceamse', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('nro_ceamse', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('calle', 'Calle', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('calle', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('nro', 'Nro', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-3">
           {!! Form::text('nro', null, ['class' => 'form-control']) !!}
        </div>
        {!! Form::label('codigo_postal', 'Código Postal', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-3">
           {!! Form::text('codigo_postal', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('entre_calle_a', 'Entre las calles', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-4">
           {!! Form::text('entre_calle_a', null, ['class' => 'form-control']) !!}
        </div>
       
        {!! Form::label('entre_calle_b', 'Y', ['class' => 'control-label col-xs-1']) !!}
        <div class="col-xs-4">
           {!! Form::text('entre_calle_b', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('localidad', 'Localidad', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
            @if ( isset ($sucursal) )
                {!! Form::text('localidad', $sucursal->provincia->nombre . ' - ' . $sucursal->localidad->nombre, ['id' => 'localidad', 'class' => 'form-control']) !!}
            @else
                {!! Form::text('localidad', null, ['id' => 'localidad', 'class' => 'form-control']) !!}
            @endif
        </div>
    </div>
    
    <div class="form-group">
        {!! Form::label('hoja_filcar', 'Hoja Filcar', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('hoja_filcar', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('chofer_id', 'Chofer', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('chofer_id', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('condicion_venta_id', 'Condición de Venta', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::select('condicion_venta_id', $options['condiciones_venta'], null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('vendedor_id', 'Vendedor', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('vendedor_id', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('estado_id', 'Estado', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::select('estado_id', $options['estados'], null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('email', 'Email', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('email', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('telefono', 'Telefono', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('telefono', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('contacto', 'Contacto', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('contacto', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('horario_atencion', 'Horario de atención', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('horario_atencion', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('recorrido_id', 'Recorrido', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('recorrido_id', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('domicilio_factura_id', 'Domicilio de Facturaci&oacute;n', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::select('domicilio_factura_id', $options['domicilios_facturacion'], null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="form-group">
        {!! Form::label('domicilio_cobro_id', 'Domicilio de Cobro', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::select('domicilio_cobro_id', $options['domicilios_cobro'], null, ['class' => 'form-control']) !!}
        </div>
    </div>    

    <div class="form-group">
        {!! Form::label('cobrador_id', 'Cobrador', ['class' => 'control-label col-xs-3']) !!}
        <div class="col-xs-9">
           {!! Form::text('cobrador_id', null, ['class' => 'form-control']) !!}
        </div>
    </div>

    <!-- Submit Field -->
    <div class="form-group text-right">
        @if ( isset ($sucursal) )
        <a class="btn" style="color:rgb(0, 112, 210)" href="{!! route('sucursales.show', ['id' => $sucursal->id]) !!}">
        @else
        <a class="btn" style="color:rgb(0, 112, 210)" href="{!! route('clientes.show', ['cliente' => $options['cliente']]) !!}">Cancelar</a>
        @endif
        {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    </div>
</div>

resources/views/sucursales/index.blade.php
@extends('app')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">Sucursales</h1>
            <a class="btn btn-default pull-right" style="margin-top: 25px; color:rgb(0, 112, 210)" href="{!! route('sucursales.create') !!}">Nuevo</a>
        </div>

        <div class="row">
            {!! Form::model(Request::all(), ['route' => 'sucursales.index', 'method' => 'GET', 'class' => 'navbar-form navbar-left pull-right', 'role' => 'search']) !!}
                <div class="form-group">
                    {!! Form::text('sucursal', null, ['class' => 'form-control', 'placeholder' => 'ID, Sucursal, Razón Social']) !!}
                    {!! Form::select('estado', $options['estados'], null, ['class' => 'form-control']) !!}
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"> </span></button>
            {!! Form::close() !!}
        </div>

        <div class="row">
            @if($sucursales->isEmpty())
                <div class="well text-center">No se encotraron sucursales.</div>
            @else
                @include('sucursales.table')
            @endif
        </div>

        @include('common.paginate', ['records' => $sucursales])

        <div class="row">
            <p>Resultados {{ $sucursales->total() }} sucursales</p>
        </div>

    </div>
@endsection

resources/views/sucursales/politicas.blade.php
<div class="box panel panel-default">
    <div class="panel-body">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12 lead">
                    Pol&iacute;tica de Precios 
                    <a class="btn btn-default pull-right small-font" href="{!! route('politicas_producto.create', ['sucursal' => $sucursal->id]) !!}">
                        <i class="glyphicon glyphicon-plus"> </i> Agregar
                    </a>
                </div>
            </div>
        </div>

        <div class="box-content">
        @if ($sucursal->politicas_productos->isEmpty())
            <div class="text-center">No se ha cargado la pol&iacute;tica de precios.</div>
        @else
            <table class="table bootstrap-datatable datatable small-font">
                <tbody>
                    @foreach ($sucursal->politicas_productos as $politica_producto)
                    <tr>
                        <td>
                            <div class="col-md-4">
                                <div class="col-md-8">{{ $politica_producto->producto->nombre }}</div>
                                <div class="col-md-2 pull-right">
                                    <a href="{!! route('domicilios_cliente.edit', ['domicilio' => $politica_producto->id]) !!}">
                                        <i class="glyphicon glyphicon-pencil"> </i>
                                    </a>
                                </div><br><br>
                                <div class="col-md-12"><b>Mensual:</b> {{ $politica_producto->cantidad_mensual }}</div>
                            </div>
                            <div class="col-md-8">
                                <table class="table bootstrap-datatable datatable small-font">
                                    <thead>
                                        <tr>
                                            <th>Hasta</th>
                                            <th>Precio</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($politica_producto->politicas_precios as $politica_precio)
                                        <tr>
                                            <td>
                                                {{ $politica_precio->cantidad_hasta }} 
                                                {{ $politica_precio->tipo_cantidad_id == 1 ?  'unidades' : 'toneladas' }}
                                            </td>
                                            <td>$ {{ $politica_precio->precio }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        </div>
    </div>
</div>

resources/views/sucursales/show.blade.php
@extends('app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 lead">
                            Sucursal <a class="btn btn-default pull-right" href="{!! route('sucursales.edit', [$sucursal->id]) !!}"><i class="glyphicon glyphicon-pencil"> </i> Editar</a>
                            <hr>
                        </div>
                            
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
                        </div>
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-12">
                                    <h1 class="only-bottom-margin">{!! $sucursal->razon_social !!}</h1>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <span class="text-muted">Nro. Cliente:</span> {!! $sucursal->nro_cliente !!}<br>
                                    <span class="text-muted">Razón social:</span> {!! $sucursal->razon_social !!}<br>
                                    <span class="text-muted">Nombre Comercial:</span> {!! $sucursal->nombre_comercial !!}<br>
                                    <span class="text-muted">CUIT:</span> {!! $sucursal->cuit !!}<br>
                                    <span class="text-muted">Estado:</span> {!! $sucursal->estado->nombre !!}<br>
                                    <span class="text-muted">Vendedor:</span> <!-- $sucursal->vendedor->persona->nombre . ' ' . $sucursal->vendedor->persona->apellido !!}--><br>
                                    <span class="text-muted">Categoría IVA:</span> {!! $sucursal->categoria_iva ? $sucursal->categoria_iva->categoria : '' !!}<br>
                                    <span class="text-muted">Condición de Venta:</span> {!! $sucursal->condicion_venta ? $sucursal->condicion_venta->condicion : '' !!}<br>
                                    <span class="text-muted">IIBB:</span> {!! $sucursal->ingresos_brutos ? $sucursal->ingresos_brutos->alicuota : '' !!}<br>
                                    <span class="text-muted">IIBB CABA:</span> {!! $sucursal->ingresos_brutos_bsas ? $sucursal->ingresos_brutos_bsas->alicuota : '' !!}<br>
                                    <span class="text-muted">Fecha Expiracion:</span> {!! $sucursal->fecha_expiracion !!}<br>
                                    <span class="text-muted">Nro Orden Compra:</span> {!! $sucursal->nro_orden_compra !!}<br>
                                </div>
                                <div>
                                    <!--<div class="activity-mini">
                                        <i class="glyphicon glyphicon-comment text-muted"></i> 500
                                    </div>
                                    <div class="activity-mini">
                                        <i class="glyphicon glyphicon-thumbs-up text-muted"></i> 1500
                                    </div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="col-lg-6">
    <!--        include('sucursales.show_facturacion')
            include('sucursales.show_cobranza')
        -->
            @include('sucursales.politicas')
        </div>

    </div>
</div>
@endsection

resources/views/sucursales/table.blade.php
<table class="table">
    <thead>
        <th>Id</th>
        <th>Sucursal</th>
        <th>Cliente</th>
        <th>Estado</th>
        <th width="50px">Action</th>
    </thead>
    <tbody>
    @foreach($sucursales as $sucursal)
        <tr>
            <td>{!! $sucursal->id !!}</td>
            <td>{!! $sucursal->nombre !!}</td>
            <td>{!! '[' . $sucursal->cliente->id . '] ' . $sucursal->cliente->razon_social !!}</td>
            <td>{!! $sucursal->estado->nombre !!}</td>
            <td class="col-xs-2">
                <a class="action-list" href="{!! route('sucursales.show', [$sucursal->id]) !!}"><i class="glyphicon glyphicon-list-alt"> </i></a>
                <a class="action-list" href="{!! route('sucursales.edit', [$sucursal->id]) !!}"><i class="glyphicon glyphicon-edit"> </i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>