app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
 
// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);

Route::get('/', 'ClienteController@index');
#Route::get('/', function () {
#    return view('app');
#});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'api', 'namespace' => 'API'], function ()
{
	Route::group(['prefix' => ''], function ()
	{
        require Config::get('generator.path_api_routes');
	});
});

Route::get('clientes/{id}/delete', [
    'as' => 'clientes.delete',
    'uses' => 'ClienteController@destroy',
]);
Route::resource('clientes', 'ClienteController');

Route::get('facturas/facturar', [
            'as'   => 'facturas.facturar',
            'uses' => 'FacturaController@facturar'
]);
Route::post('facturas/facturar', [
            'as'   => 'facturas.facturar',
            'uses' => 'FacturaController@facturar'
]);

Route::get('facturas/imprimir', 'FacturaController@imprimir');
Route::post('facturas/imprimir', [
            'as'   => 'facturas.imprimir',
            'uses' => 'FacturaController@imprimir'
]);

Route::post('facturas/getPendientesFacturacion', 'FacturaController@getPendientesFacturacion');
Route::post('facturas/facturarBySucursal', 'FacturaController@facturarBySucursal');
Route::get('facturas/facturarAfip', 'FacturaController@facturarAfip');

Route::get('facturas/facturacion', [
            'as'   => 'facturas.facturacion',
            'uses' => 'FacturaController@facturacion'
]);
Route::resource('facturas', 'FacturaController');

Route::resource('servicios', 'ServicioController');

Route::get('localidad/getLocalidadesAutocomplete', 'LocalidadController@getLocalidadesAutocomplete');

Route::resource('domicilios_cliente', 'DomicilioClienteController');

Route::get('sucursales/getDatosClienteFactura', 'SucursalController@getDatosClienteFactura');
Route::get('sucursales/getSucursalesAutocomplete', 'SucursalController@getSucursalesAutocomplete');
Route::get('sucursales/getSucursalesActivasAutocomplete', 'SucursalController@getSucursalesActivasAutocomplete');
Route::get('sucursales/getSucursalesActivasByNroClienteAutocomplete', 'SucursalController@getSucursalesActivasByNroClienteAutocomplete');
Route::resource('sucursales', 'SucursalController');


Route::get('productos/getProductosAutocomplete', 'ProductoController@getProductosAutocomplete');
Route::resource('productos', 'ProductoController');

Route::get('productos/{id}/delete', [
    'as' => 'productos.delete',
    'uses' => 'ProductoController@destroy',
]);

Route::get('politicas_producto/getProductosBySucursal', 'PoliticaProductoController@getProductosBySucursal');
Route::get('politicas_producto/getProductosBySucursalAutocomplete', 'PoliticaProductoController@getProductosBySucursalAutocomplete');
Route::resource('politicas_producto', 'PoliticaProductoController');

Route::get('politicas_producto/{id}/delete', [
    'as' => 'politicas_producto.delete',
    'uses' => 'PoliticaProductoController@destroy',
]);

Route::get('politicas_precios/getPrecioForItem', 'PoliticaPrecioController@getPrecioForItem');

/*
Route::get('clientes/{id}/delete', [
    'as' => 'clientes.delete',
    'uses' => 'ClienteController@destroy',
]);
*/

app/Models/Cliente.php
<?php namespace Hanzo\Models;

use Illuminate\Database\Eloquent\Model as Model;
#use Hanzo\Models\Tipo;

class Cliente extends Model
{
    
	public $table = "clientes";
    

	public $fillable = [
	    "nro_cliente",
		"razon_social",
		"nombre_comercial",
		"cuit",
		"estado_id",
		"vendedor_id",
		"categoria_iva_id",
		"condicion_venta_id",
		"ingreso_brutos_id",
		"ingreso_brutos_bsas_id",
		"fecha_expiracion",
		"grupo_empresario_id",
		"web",
		"cuota_mensual",
        "tipo_cliente_id",
		"created_user_id"
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "nro_cliente" => "integer",
        "razon_social" => "string",
        "nombre_comercial" => "string",
        "cuit" => "string",
        "estado_id" => "integer",
        "vendedor_id" => "integer",
        "categoria_iva_id" => "integer",
        "condicion_venta_id" => "integer",
        "ingreso_brutos_id" => "integer",
        "ingreso_brutos_bsas_id" => "integer",
        "grupo_empresario_id" => "integer",
        "web" => "string",
        "cuota_mensual" => "double",
        "tipo_cliente_id" => "integer",
        "created_user_id" => "integer",
        "updated_user_id" => "integer",
        "deleted_user_id" => "integer"
    ];

	public static $rules = [
        "razon_social" => "required",
		"estado_id" => "required"
	];

    public function estado()
    {
        return $this->belongsTo(EstadosCliente::class);
    }

    public function categoria_iva()
    {
        return $this->belongsTo(CategoriaIva::class);
    }

    public function tipo_cliente()
    {
        return $this->belongsTo(TipoCliente::class);
    }
    
    public function ingresos_brutos()
    {
        return $this->belongsTo(Alicuota::class);
    }

    public function ingresos_brutos_bsas()
    {
        return $this->belongsTo(Alicuota::class);
    }

    public function vendedor()
    {
        return $this->belongsTo(Vendedor::class);
    }

    public function rubro_empresario()
    {
        return $this->belongsTo(RubroEmpresario::class);
    }

    public function politicas_productos()
    {
        return $this->hasMany(PoliticaProducto::class);
    }

    public function sucursales()
    {
        return $this->hasMany(Sucursal::class);
    }

    public function pendientes()
    {
        return $this->hasMany(Pendiente::class)->where('estado_id', 1);
    }

    public function historico()
    {
        return $this->hasMany(Historico::class);
    }

    public function domicilios_facturacion()
    {
        $tipo = TipoDomicilioCliente::where('nombre', 'ftc')->first();

        return $this->hasMany(DomicilioCliente::class)->where('tipo_domicilio_cliente_id', $tipo->id);
    }

    public function domicilios_cobro()
    {
        $tipo = TipoDomicilioCliente::where('nombre', 'cbz')->first();

        return $this->hasMany(DomicilioCliente::class)->where('tipo_domicilio_cliente_id', $tipo->id);
    }

    public function scopeCliente($query, $cliente)
    {
        if (trim($cliente) != '')
        {
            if ( is_numeric($cliente) )
            {
                if (strlen($cliente) < 10) 
                {
                    $query->where('id', $cliente);
                    $query->orWhere('cuit', $cliente);
                } else {
                    $query->where('cuit', $cliente);
                }
            } else {
                $query->where('razon_social', 'ilike', '%' . $cliente . '%');
            }
        }
    }

    public function scopeByEstado($query, $estado)
    {
        if (trim($estado) && is_numeric($estado))
            $query->where('estado_id', $estado);
    }

    public function getTotalPendientes()
    {
        $pendientes = $this->pendientes;
        $total = 0;

        if (!$pendientes)
            return $total;

        foreach ($pendientes as $pendiente) 
        {
            if ($pendiente->tipo_comprobante->codigo == 'NCRE')
                $total-= $pendiente->importe;
            else
                $total+= $pendiente->importe;
        }

        return $total;
    }
}

app/Http/Controllers/ClienteController.php
<?php namespace Hanzo\Http\Controllers;

use Hanzo\Http\Requests;
use Illuminate\Http\Request;
use Hanzo\Models\Cliente;
use Hanzo\Models\EstadosCliente;
use Hanzo\Models\CategoriaIva;
use Hanzo\Models\CondicionVenta;
use Hanzo\Models\Alicuota;
use Hanzo\Models\TipoCliente;
use Hanzo\Http\Requests\CreateClienteRequest;
use Hanzo\Http\Requests\UpdateClienteRequest;
use Hanzo\Libraries\Repositories\ClienteRepository;
use Flash;
use Mitul\Controller\AppBaseController as AppBaseController;
use Response;

class ClienteController extends AppBaseController
{

	/** @var  ClienteRepository */
	private $clienteRepository;

	function __construct(ClienteRepository $clienteRepo)
	{
        $this->middleware('auth');
		$this->clienteRepository = $clienteRepo;
	}

	/**
	 * Display a listing of the Cliente.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
        $clientes = Cliente::cliente($request->get('cliente'))->byEstado($request->get('estado'))->orderBy('id', 'ASC')->paginate();
        $options = array('estados' => ['' => ''] + EstadosCliente::lists('nombre', 'id')->all());
        $query = array();
        
        if ($request->get('cliente') != '')
		  $query['cliente'] = $request->get('cliente');

        if ($request->get('estado') != '')
          $query['estado'] = $request->get('estado');

        return view('clientes.index')
            ->with('clientes', $clientes)
            ->with('options', $options)
			->with('query', $query);
	}

	/**
	 * Show the form for creating a new Cliente.
	 *
	 * @return Response
	 */
	public function create()
	{
        $options = array();
        $options['estados'] = ['' => ''] + EstadosCliente::lists('nombre', 'id')->all();
        $options['categorias_iva'] = ['' => ''] + CategoriaIva::lists('categoria', 'id')->all();
        $options['condiciones_venta'] = ['' => ''] + CondicionVenta::lists('condicion', 'id')->all();
        $options['tipos_cliente'] = ['' => ''] + TipoCliente::lists('nombre', 'id')->all();
        $options['ingresos_brutos'] = ['' => ''] + Alicuota::where('codigo', '>', '20')->lists('alicuota', 'id')->all();

        return view('clientes.create')->with('options', $options);
	}

	/**
	 * Store a newly created Cliente in storage.
	 *
	 * @param CreateClienteRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateClienteRequest $request)
	{
        $input = $request->all();
        $input['created_user_id'] = $request->user()->id;

        foreach ($input as $clave => $valor) 
        {
            if (trim($valor) == '')
                unset($input[$clave]);
        }

        $cliente = $this->clienteRepository->create($input);

        Flash::success('El Cliente fue guardado correctamente.');

        return redirect(route('clientes.show', array('id' => $cliente->id)));
	}

	/**
	 * Display the specified Cliente.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$cliente = $this->clienteRepository->find($id);

		if(empty($cliente))
		{
			Flash::error('Cliente no encontrado');

			return redirect(route('clientes.index'));
		}

        $scripts = array('clientes_show.js');

		return view('clientes.show')
                    ->with('scripts', $scripts)
                    ->with('cliente', $cliente);
	}

	/**
	 * Show the form for editing the specified Cliente.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id)
	{
		$cliente = $this->clienteRepository->find($id);

		if(empty($cliente))
		{
			Flash::error('Cliente no encontrado');

			return redirect(route('clientes.index'));
		}

        $options = array();
        $options['estados'] = ['' => ''] + EstadosCliente::lists('nombre', 'id')->all();
        $options['categorias_iva'] = ['' => ''] + CategoriaIva::lists('categoria', 'id')->all();
        $options['condiciones_venta'] = ['' => ''] + CondicionVenta::lists('condicion', 'id')->all();
        $options['ingresos_brutos'] = ['' => ''] + Alicuota::where('codigo', '>', '20')->lists('alicuota', 'id')->all();
        $options['tipos_cliente'] = ['' => ''] + TipoCliente::lists('nombre', 'id')->all();
        
        return view('clientes.edit')->with('cliente', $cliente)->with('options', $options);
	}

	/**
	 * Update the specified Cliente in storage.
	 *
	 * @param  int              $id
	 * @param UpdateClienteRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdateClienteRequest $request)
	{
		$cliente = $this->clienteRepository->find($id);

		if(empty($cliente))
		{
			Flash::error('Cliente no encontrado');

			return redirect(route('clientes.index'));
		}

        $input = $request->all();
        $input['updated_user_id'] = $request->user()->id;

        foreach ($input as $clave => $valor) 
        {
            if (trim($valor) == '')
                unset($input[$clave]);
        }

		$cliente = $this->clienteRepository->updateRich($input, $id);

		Flash::success('Cliente actualizado correctamente.');

        return redirect(route('clientes.show', array('id' => $id)));
	}

	/**
	 * Remove the specified Cliente from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		$cliente = $this->clienteRepository->find($id);

		if(empty($cliente))
		{
			Flash::error('Cliente no encontrado');

			return redirect(route('clientes.index'));
		}

		$this->clienteRepository->delete($id);

		Flash::success('Cliente eliminado correctamente.');

		return redirect(route('clientes.index'));
	}
}

resources/views/clientes/show.blade.php
@extends('app')

@section('content')
<div class="container">
	 @include('clientes.show_fields')
</div>
@endsection

resources/views/clientes/show_cobranza.blade.php
<div class="box panel-default">
    <div class="panel-body">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12 lead">
                    Domicilio de cobro 

                    @if( !$cliente->domicilio_cobro )
                    <a class="btn btn-default pull-right small-font" href="{!! route('domicilios_cliente.create', ['cliente' => $cliente->id, 'tipo' => 'cbz']) !!}">
                        <i class="glyphicon glyphicon-plus"> </i> Agregar
                    </a>
                    @else
                    <a class="btn btn-default pull-right small-font" href="{!! route('domicilios_cliente.edit', ['domicilio' => $cliente->domicilio_cobro->id]) !!}">
                        <i class="glyphicon glyphicon-pencil"> </i> Editar
                    </a>
                    @endif
                </div>
            </div>
        </div>

        <div class="box-content small-font pre-scrollable">
        @if( $cliente->domicilios_cobro->isEmpty() )
            <div class="text-center">No se encotraron domicilios de cobro.</div>
        @else
            <table class="table bootstrap-datatable datatable small-font">
                <thead>
                    <tr>
                        <th>Domicilio</th>
                        <th>Localidad</th>
                        <th>Teléfono</th>
                        <th></th>
                    </tr>
                </thead>   
                <tbody>
                    @foreach ($cliente->domicilios_cobro as $domicilio)
                    <tr>
                        <td>{{ $domicilio->calle }} {{ $domicilio->nro }}</td>
                        <td>{{ $domicilio->localidad->nombre }} - {{ $domicilio->provincia->nombre }}</td>
                        <td>{{ $domicilio->telefono }}</td>
                        <td>
                            <a class="pull-right" href="{!! route('domicilios_cliente.edit', ['domicilio' => $domicilio->id]) !!}">
                                <i class="glyphicon glyphicon-pencil"> </i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        </div>
    </div>
</div>

resources/views/clientes/show_facturacion.blade.php
<div class="box panel-default">
    <div class="panel-body">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12 lead">
                    Domicilio de facturación 

                    @if( !$cliente->domicilio_facturacion )
                    <a class="btn btn-default pull-right small-font" href="{!! route('domicilios_cliente.create', ['cliente' => $cliente->id, 'tipo' => 'ftc']) !!}">
                        <i class="glyphicon glyphicon-plus"> </i> Agregar
                    </a>
                    @else
                    <a class="btn btn-default pull-right small-font" href="{!! route('domicilios_cliente.edit', ['domicilio' => $cliente->domicilio_facturacion->id]) !!}">
                        <i class="glyphicon glyphicon-pencil"> </i> Editar
                    </a>
                    @endif
                </div>
            </div>
        </div>

        <div class="box-content small-font pre-scrollable">
        @if( $cliente->domicilios_facturacion->isEmpty() )
            <div class="text-center">No se encotraron domicilios de facturaci&oacite;n.</div>
        @else
            <table class="table bootstrap-datatable datatable small-font">
                <thead>
                    <tr>
                        <th>Domicilio</th>
                        <th>Localidad</th>
                        <th>Teléfono</th>
                        <th></th>
                    </tr>
                </thead>   
                <tbody>
                    @foreach ($cliente->domicilios_facturacion as $domicilio)
                    <tr>
                        <td>{{ $domicilio->calle }} {{ $domicilio->nro }}</td>
                        <td>{{ $domicilio->localidad->nombre }} - {{ $domicilio->provincia->nombre }}</td>
                        <td>{{ $domicilio->telefono }}</td>
                        <td>
                            <a class="pull-right" href="{!! route('domicilios_cliente.edit', ['domicilio' => $domicilio->id]) !!}">
                                <i class="glyphicon glyphicon-pencil"> </i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>             
        @endif
        </div>
    </div>
</div>

resources/views/clientes/show_politicas_precios.blade.php
<div class="box panel-default">
    <div class="panel-body">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12 lead">
                    Pol&iacute;tica de Precios 
                    <a class="btn btn-default pull-right small-font" href="{!! route('politicas_producto.create', ['cliente' => $cliente->id]) !!}">
                        <i class="glyphicon glyphicon-plus"> </i> Agregar
                    </a>
                </div>
            </div>
        </div>

        <div class="box-content">
        @if ($cliente->politicas_productos->isEmpty())
            <div class="text-center">No se ha cargado la pol&iacute;tica de precios.</div>
        @else
            <table class="table bootstrap-datatable datatable small-font">
                <tbody>
                    @foreach ($cliente->politicas_productos as $politica_producto)
                    <tr>
                        <td>
                            <div class="col-md-4">
                                <div class="col-md-8">{{ $politica_producto->producto->nombre }}</div>
                                <div class="col-md-2 pull-right">
                                    <a href="{!! route('domicilios_cliente.edit', ['domicilio' => $politica_producto->id]) !!}">
                                        <i class="glyphicon glyphicon-pencil"> </i>
                                    </a>
                                </div><br><br>
                                <div class="col-md-12"><b>Mensual:</b> {{ $politica_producto->cantidad_mensual }}</div>
                            </div>
                            <div class="col-md-8">
                                <table class="table bootstrap-datatable datatable small-font">
                                    <thead>
                                        <tr>
                                            <th>Hasta</th>
                                            <th>Precio</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($politica_producto->politicas_precios as $politica_precio)
                                        <tr>
                                            <td>
                                                {{ $politica_precio->cantidad_hasta }} 
                                                {{ $politica_precio->tipo_cantidad_id == 1 ?  'unidades' : 'toneladas' }}
                                            </td>
                                            <td>$ {{ $politica_precio->precio }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        </div>
    </div>
</div>

resources/views/clientes/show_sucursales.blade.php
<div class="box panel-default">
    <div class="panel-body">
        <div class="box-header">
            <div class="row">
                <div class="col-md-12 lead">
                    Sucursales 
                    <a class="btn btn-default pull-right small-font" href="{!! route('sucursales.create', ['cliente' => $cliente->id]) !!}">
                        <i class="glyphicon glyphicon-plus"> </i> Agregar
                    </a>
                </div>
            </div>
        </div>

        <div class="box-content">
        @if($cliente->sucursales->isEmpty())
            <div class="text-center">No se encontraron sucursales.</div>
        @else
            <div id="tabs-sucursales">
                <ul class="col-lg-6 pre-scrollable">
                    @foreach ($cliente->sucursales as $sucursal)
                    <li>
                        <a href="#tabs-suc-{{ $sucursal->id }}" class="col-md-12">
                            {{ $sucursal->nombre }}
                        </a>
                    </li>
                    @endforeach
                </ul>

                <div class="col-lg-6">
                @foreach ($cliente->sucursales as $sucursal)
                    <div id="tabs-suc-{{ $sucursal->id }}" class="col-md-12">
                        <div class="row lead">
                            {{ $sucursal->nombre }} 
                            <a class="pull-right" href=" {{ route('sucursales.edit', ['sucursal' => $sucursal->id] ) }}">
                                <i class="glyphicon glyphicon-pencil"> </i>
                            </a> 
                        </div>

                        <div class="tabs-info-sucursal ui-tabs-horizontal">
                            <ul>
                                <li><a class="col-lg-12" href="#tabs-suc-{{ $sucursal->id }}-1">Políticas de Precios</a>
                                <li><a class="col-lg-12" href="#tabs-suc-{{ $sucursal->id }}-2">
                                    Servicios {{ $sucursal->getServiciosPendientes()->count() > 0 ? '(' . $sucursal->getServiciosPendientes()->count() . ')' : '' }}  
                                </a></li>
                                <li><a class="col-lg-12" href="#tabs-suc-{{ $sucursal->id }}-3">Facturas</a></li>
                            </ul>

                            <div id="tabs-suc-{{ $sucursal->id }}-1" class="col-lg-12 pre-scrollable">
                            @if ( $sucursal->politicas_productos->isEmpty() )
                                <div class="text-center">No se definieron políticas.</div>
                            @else
                                <table class="table bootstrap-datatable datatable small-font">
                                    <thead>
                                        <tr>
                                            <th>Producto</th>
                                            <th>Mensual</th>
                                            <th>Hasta</th>
                                            <th>Precio</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($sucursal->politicas_productos as $politica_producto)
                                        @if ($politica_producto->politicas_precios->isEmpty())
                                        <tr>
                                            <th rowspan="{{ count($politica_producto->politicas_precios) }}">
                                                <div class="col-md-8">{{ $politica_producto->producto->nombre }}</div>
                                                <div class="col-md-2 pull-right">
                                                    <a href="{!! route('domicilios_cliente.edit', ['domicilio' => $politica_producto->id]) !!}">
                                                        <i class="glyphicon glyphicon-pencil"> </i>
                                                    </a>
                                                </div>
                                            </th>
                                            <td rowspan="{{ count($politica_producto->politicas_precios) }}">
                                                {{ $politica_producto->cantidad_mensual ? $politica_producto->cantidad_mensual : 0 }} uni.
                                            </td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        @else
                                        @foreach ($politica_producto->politicas_precios as $key => $politica_precio)
                                            <tr>
                                            @if ( $key == 0 )
                                                <th rowspan="{{ count($politica_producto->politicas_precios) }}">
                                                    <div class="col-md-8">{{ $politica_producto->producto->nombre }}</div>
                                                    <div class="col-md-2 pull-right">
                                                        <a href="{!! route('domicilios_cliente.edit', ['domicilio' => $politica_producto->id]) !!}">
                                                            <i class="glyphicon glyphicon-pencil"> </i>
                                                        </a>
                                                    </div>
                                                </th>
                                                <td rowspan="{{ count($politica_producto->politicas_precios) }}">
                                                    {{ $politica_producto->cantidad_mensual ? $politica_producto->cantidad_mensual : 0 }} uni.
                                                </td>
                                            @endif
                                                <td>
                                                    {{ $politica_precio->cantidad_hasta }} 
                                                    {{ $politica_precio->tipo_cantidad_id == 1 ?  'uni' : 'ton' }}
                                                </td>
                                                <td>$ {{ $politica_precio->precio }}</td>
                                            </tr>
                                        @endforeach
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif

                            </div>

                            <!-- Servicios pendientes-->
                            <div id="tabs-suc-{{ $sucursal->id }}-2" class="col-lg-12 pre-scrollable">
                            @if ( $sucursal->getServiciosPendientes()->isEmpty() )
                                <div class="text-center">No se tiene servicios pendientes.</div>
                            @else<table class="table bootstrap-datatable datatable small-font">
                                    <thead>
                                        <tr>
                                            <th>Fecha</th>
                                            <th>Producto</th>
                                            <th>Contenido</th>
                                            <th>Estado</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($sucursal->getServiciosPendientes() as $servicio)
                                        <tr>
                                            <td>{{ date('d-m-Y', strtotime($servicio->fecha)) }}</td>
                                            <td>{{ $servicio->producto->nombre }}</td>
                                            <td>{{ $servicio->contenedores }} cont./ {{ $servicio->kilos }} kg</td>
                                            <td>{!! $servicio->estado_id == 1 ? 'Pendiente' : ($servicio->estado_id == 2 ? 'Facturado' : 'ERR' ) !!}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif
                            </div>

                            <!-- Facturas pendientes
                            <div id="tabs-suc-{{ $sucursal->id }}-3" class="col-lg-12">
                                <table class="table bootstrap-datatable datatable small-font">
                                    <thead>
                                        <tr>
                                            <th>Numero</th>
                                            <th>Tipo</th>
                                            <th>Total</th>
                                            <th>Fecha</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($sucursal->facturas->sortByDesc('numero') as $factura)
                                        <tr>
                                            <td>{{ $factura->numero }}</td>
                                            <td>{{ $factura->letra }}</td>
                                            <td class="text-right">$ {!! number_format($factura->total, 2, '.', ',') !!}</td>
                                            <td>{{ date('d-m-Y', strtotime($factura->fecha)) }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            -->
                        </div>

                    </div>
                @endforeach
                </div>
            </div>
        @endif
        </div>
    </div>
</div>